# Generated by Django 4.2.13 on 2024-06-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('CLIENT', 'Client')], default='CLIENT', max_length=30, verbose_name='Rôle'),
        ),
    ]
